# name of the software
name: jQuery QueryBuilder
# current version of the software
version: 2.4.1
# url of the download button
downloadUrl: https://github.com/mistic100/jQuery-QueryBuilder
# links to file/dir viewers
treeUrl: https://github.com/mistic100/jQuery-QueryBuilder/tree/master
blobUrl: https://github.com/mistic100/jQuery-QueryBuilder/blob/master
cdnUrl: https://cdn.jsdelivr.net/jquery.query-builder/2.4.0
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

customNavBar: true

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/mistic100/jQuery-QueryBuilder
  - title: StrangePlanet
    url: http://www.strangeplanet.fr

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/mistic100/jQuery-QueryBuilder
  - title: Issues
    url: https://github.com/mistic100/jQuery-QueryBuilder/issues?state=open

# header
header:
  color1: "#0074d9"
  color2: "#001f3f"
  trianglify: true

# google analytics
analytics:
  account: UA-28192323-3
  domain: auto

# github button
githubButton:
  user: mistic100
  repo: jQuery-QueryBuilder

# twitter buttons
twitter:
  enabled: true
  via: mistic100
  hash: jQuery,QueryBuilder
  account: mistic100

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-redirect-from
